<?php

namespace Orange\HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SousTypologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTypologieRepository extends EntityRepository
{
}
